select * from SYS.SYSTABLES  where TABLETYPE='T'

select * from SYS.SYSCOLUMNS
 
-- DROP TABLE APP.DEP

CREATE TABLE APP.DEP
   (	DEPID INT PRIMARY KEY,
    	DEPNAME VARCHAR(10)
   );   

-- DROP TABLE APP.EMP
   
CREATE TABLE APP.EMP
   (	EMPID INT PRIMARY KEY,
    	EMPNAME VARCHAR(12), 
    	Age int,
    	EMPSTATUS VARCHAR(1),
    	DEPID int  REFERENCES DEP(DEPID)
    );   
    
   -- Person  Table

-- DROP TABLE APP.PERSON

CREATE TABLE APP.PERSON
    (ID INT not null  PRIMARY KEY  
        GENERATED ALWAYS AS IDENTITY
        (START WITH 101, INCREMENT BY 1),    
    NAME VARCHAR(12) NOT NULL ,   SEX CHAR(1), AGE int ); 
  
 